version: '3'
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.23"
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
     - "script.painless.regex.enabled=true"
     - "xpack.security.enabled=false"
  web:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile
    command: multiscanner-web
    ports:
     - "8000:8000"
  api:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile
    volumes:
     - "/var/run/clamav:/var/run/clamav"
    command: /wait-for-it.sh elastic:9200 -- multiscanner-api
    ports:
     - "127.0.0.1:8080:8080"
    depends_on:
     - elastic
